import { useEffect, useState, useRef } from 'react'
import { useParams, useNavigate, useLocation } from 'react-router-dom'
import { ArrowLeft, ChevronDown, ChevronRight, AlertTriangle, RotateCcw, PenLine, Loader, Download, Copy, FileText, Check } from 'lucide-react'
import { getCheck, saveCheck } from '../lib/storage'
import { submitCheck } from '../lib/api'
import ScoreGauge from '../components/ScoreGauge'

const RISK_COLOR = { HIGH: 'var(--red)', MEDIUM: 'var(--amber)', LOW: 'var(--green)' }

function formatDateAU(dateStr) {
  if (!dateStr) return null
  const [y, m, d] = String(dateStr).split('-')
  if (!d) return dateStr
  return `${d}/${m}/${y}`
}
const LAYER_NAME = {
  sanctions:    'Sanctions & Watchlists',
  pep:          'PEP Screening',
  adverseMedia: 'Adverse Media',
  corporate:    'Corporate Intelligence',
  crypto:       'Crypto Wallet',
}

export default function Report() {
  const { checkId } = useParams()
  const navigate = useNavigate()
  const location = useLocation()
  // Seed state from navigation (rerun passes the new report directly — no localStorage flash)
  const [report, setReport] = useState(location.state?.report || null)
  const [open, setOpen] = useState({})
  const [rerunning, setRerunning] = useState(false)
  const [exportOpen, setExportOpen] = useState(false)
  const [copied, setCopied] = useState(false)
  const exportRef = useRef(null)

  useEffect(() => {
    function handleClickOutside(e) {
      if (exportRef.current && !exportRef.current.contains(e.target)) setExportOpen(false)
    }
    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [])

  function buildCopyText(r) {
    const lines = []
    lines.push(`CLEARPATH SCREENING REPORT`)
    lines.push(`${'─'.repeat(40)}`)
    lines.push(`Subject:    ${r.subject?.fullName}`)
    if (r.subject?.dateOfBirth) lines.push(`DOB:        ${r.subject.dateOfBirth}`)
    if (r.subject?.nationality) lines.push(`Nationality: ${r.subject.nationality}`)
    lines.push(`Screened:   ${new Date(r.createdAt).toLocaleString()}`)
    lines.push(`Risk Level: ${r.riskLevel}  |  Score: ${r.score}/100`)
    lines.push('')
    if (r.explanation) {
      lines.push(`ANALYSIS SUMMARY`)
      lines.push(r.explanation)
      lines.push('')
    }
    const pep = r.layers?.pep
    if (pep?.pepConfirmed) {
      lines.push(`PEP SCREENING - CONFIRMED`)
      pep.strongMatches?.forEach(m => {
        lines.push(`  Match: ${m.matchedName} (${m.pepClassification?.label || 'PEP'})`)
        if (m.positions?.length) lines.push(`  Positions: ${m.positions.join(', ')}`)
        if (m.country) lines.push(`  Country: ${m.country}`)
      })
      lines.push('')
    }
    const media = r.layers?.adverseMedia
    if (media?.findings?.length) {
      lines.push(`ADVERSE MEDIA - ${media.findingsCount} FINDING(S)`)
      media.findings.forEach(f => {
        lines.push(`  [${f.severity}] ${f.title || '(no title)'}`)
        lines.push(`  Source: ${f.sourceName || f.source}${f.publishedAt ? `  |  ${f.publishedAt.slice(0,10)}` : ''}`)
        if (f.keywords?.length) lines.push(`  Keywords: ${f.keywords.join(', ')}`)
      })
      lines.push('')
    }
    if (r.recommendations?.length) {
      lines.push(`RECOMMENDATIONS`)
      r.recommendations.forEach((rec, i) => lines.push(`  ${i + 1}. ${rec}`))
      lines.push('')
    }
    lines.push(`Check ID: ${r.checkId}`)
    lines.push(`Generated by ClearPath`)
    return lines.join('\n')
  }

  async function handleCopySummary() {
    try {
      await navigator.clipboard.writeText(buildCopyText(report))
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {}
    setExportOpen(false)
  }

  function handleExportPdf() {
    setExportOpen(false)
    setTimeout(() => window.print(), 100)
  }

  async function handleRerun() {
    if (!report) return
    setRerunning(true)
    try {
      const newReport = await submitCheck({
        ...report.subject,
        checkLayers: report.checkLayers?.length ? report.checkLayers : Object.keys(report.layers).filter(k => report.layers[k]),
      })
      newReport._rerunOf = report.checkId
      // Pass report through state so new page renders instantly — no localStorage round-trip flash
      navigate(`/checks/${newReport.checkId}`, { state: { report: newReport } })
    } catch (err) {
      console.error('Rerun failed', err)
      setRerunning(false)
    }
  }

  function handleEdit() {
    navigate('/checks/new', {
      state: {
        prefill: report.subject,
        layers: report.checkLayers?.length
          ? report.checkLayers
          : Object.keys(report.layers).filter(k => report.layers[k]),
      }
    })
  }

  useEffect(() => {
    // If we already have the report from navigation state, just persist it to storage
    if (location.state?.report) {
      saveCheck(location.state.report)
      return
    }
    const r = getCheck(checkId)
    if (r) setReport(r)
  }, [checkId])

  if (!report) return (
    <div style={{ padding: '60px 40px', display: 'flex', alignItems: 'center', gap: 12, color: 'var(--tx-3)' }}>
      <Loader size={16} style={{ animation: 'spin 0.8s linear infinite', flexShrink: 0 }} />
      <span style={{ fontSize: 13 }}>Loading report...</span>
    </div>
  )

  const riskColor = RISK_COLOR[report.riskLevel] || 'var(--tx-2)'
  const layers = Object.entries(report.layers || {}).filter(([, v]) => v)
  const toggle = k => setOpen(p => ({ ...p, [k]: !p[k] }))

  return (
    <div>

      {/* Rerun overlay - makes it unmistakably clear a new check is running */}
      {rerunning && (
        <div style={{
          position: 'fixed', inset: 0, zIndex: 100,
          background: 'rgba(11,14,20,0.88)', backdropFilter: 'blur(6px)',
          display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 20,
        }}>
          <Loader size={32} color="var(--accent)" style={{ animation: 'spin 0.8s linear infinite' }} />
          <div style={{ textAlign: 'center' }}>
            <div style={{ fontSize: 18, fontWeight: 700, color: 'var(--tx)', marginBottom: 6 }}>
              Re-screening {report.subject?.fullName}
            </div>
            <div style={{ fontSize: 13, color: 'var(--tx-3)', marginBottom: 4 }}>
              Running a fresh check with the same parameters.
            </div>
            <div style={{ fontSize: 12, color: 'var(--tx-3)' }}>
              A new report will be saved as a separate log entry.
            </div>
          </div>
          <div style={{ display: 'flex', gap: 16, marginTop: 8, fontSize: 12, color: 'var(--tx-3)' }}>
            {(report.checkLayers?.length
              ? report.checkLayers
              : Object.keys(report.layers || {}).filter(k => report.layers[k])
            ).map(l => (
              <span key={l} style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 4, padding: '3px 10px' }}>{l}</span>
            ))}
          </div>
        </div>
      )}

      {/* Topbar */}
      <div className="no-print" style={{
        position: 'sticky', top: 0, zIndex: 10,
        display: 'flex', alignItems: 'center', gap: 12,
        padding: '0 28px', height: 44,
        background: 'var(--surface)', borderBottom: '1px solid var(--border)',
      }}>
        <button onClick={() => navigate('/dashboard')} style={{ display: 'flex', alignItems: 'center', gap: 6, background: 'none', border: 'none', color: 'var(--tx-3)', cursor: 'pointer', fontSize: 12, padding: '4px 0' }}>
          <ArrowLeft size={13} /> Dashboard
        </button>
        <span style={{ color: 'var(--border)', fontSize: 16 }}>·</span>
        <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--tx-2)' }}>{report.subject?.fullName}</span>
        <span style={{ color: 'var(--border)', fontSize: 16 }}>·</span>
        <span style={{ fontFamily: 'monospace', fontSize: 11, color: 'var(--tx-3)' }}>{report.checkId}</span>
        {report._rerunOf && (
          <span style={{ fontSize: 11, color: 'var(--tx-3)', background: 'var(--raised)', border: '1px solid var(--border)', borderRadius: 4, padding: '2px 8px' }}>
            rerun of <span style={{ fontFamily: 'monospace' }}>{report._rerunOf.slice(0, 8)}…</span>
          </span>
        )}
        <div style={{ flex: 1 }} />
        <button onClick={handleEdit} title={`Edit parameters and re-screen ${report.subject?.fullName}`} style={{ display: 'flex', alignItems: 'center', gap: 6, background: 'none', border: '1px solid var(--border)', borderRadius: 5, color: 'var(--tx-3)', cursor: 'pointer', fontSize: 12, padding: '5px 12px' }}>
          <PenLine size={12} /> Edit & rerun
        </button>
        <button
          onClick={handleRerun}
          disabled={rerunning}
          title={`Re-run screening for ${report.subject?.fullName} with the same parameters. A new log entry will be created.`}
          style={{ display: 'flex', alignItems: 'center', gap: 6, background: rerunning ? 'var(--raised)' : 'var(--accent)', border: 'none', borderRadius: 5, color: rerunning ? 'var(--tx-3)' : '#fff', cursor: rerunning ? 'wait' : 'pointer', fontSize: 12, padding: '5px 12px' }}
        >
          {rerunning ? <Loader size={12} style={{ animation: 'spin 0.8s linear infinite' }} /> : <RotateCcw size={12} />}
          {rerunning ? `Re-screening ${report.subject?.fullName?.split(' ')[0]}…` : 'Rerun'}
        </button>
        <div ref={exportRef} style={{ position: 'relative' }}>
          <button
            onClick={() => setExportOpen(p => !p)}
            style={{ display: 'flex', alignItems: 'center', gap: 6, background: 'none', border: '1px solid var(--border)', borderRadius: 5, color: copied ? 'var(--green)' : 'var(--tx-3)', cursor: 'pointer', fontSize: 12, padding: '5px 12px' }}
          >
            {copied ? <Check size={12} /> : <Download size={12} />}
            {copied ? 'Copied!' : 'Export'}
            <ChevronDown size={10} style={{ opacity: 0.5 }} />
          </button>
          {exportOpen && (
            <div style={{
              position: 'absolute', top: 'calc(100% + 6px)', right: 0, zIndex: 50,
              background: 'var(--surface)', border: '1px solid var(--border-2)', borderRadius: 7,
              boxShadow: '0 8px 24px rgba(0,0,0,0.4)', minWidth: 200, overflow: 'hidden',
            }}>
              <button onClick={handleCopySummary} style={S.dropItem}>
                <Copy size={13} style={{ flexShrink: 0 }} />
                <div>
                  <div style={{ fontWeight: 600, marginBottom: 2 }}>Copy summary</div>
                  <div style={{ fontSize: 11, color: 'var(--tx-3)' }}>AI summary + findings as plain text</div>
                </div>
              </button>
              <div style={{ height: 1, background: 'var(--border)' }} />
              <button onClick={handleExportPdf} style={S.dropItem}>
                <FileText size={13} style={{ flexShrink: 0 }} />
                <div>
                  <div style={{ fontWeight: 600, marginBottom: 2 }}>Export as PDF</div>
                  <div style={{ fontSize: 11, color: 'var(--tx-3)' }}>Full report - print or save as PDF</div>
                </div>
              </button>
            </div>
          )}
        </div>
      </div>

      <div style={{ padding: '36px 40px', maxWidth: 820 }}>

        {/* Hard stop */}
        {report.hardStop && (
          <div style={{ display: 'flex', gap: 14, padding: '14px 18px', background: 'rgba(255,77,77,0.06)', border: '1px solid rgba(255,77,77,0.25)', borderRadius: 8, marginBottom: 24 }}>
            <AlertTriangle size={18} color="var(--red)" style={{ flexShrink: 0, marginTop: 1 }} />
            <div>
              <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--red)', marginBottom: 2 }}>Sanctions hard stop</div>
              <div style={{ fontSize: 12, color: 'var(--tx-2)', lineHeight: 1.6 }}>
                This subject matches a sanctioned entity. Onboarding must not proceed. Escalate to your compliance officer immediately.
              </div>
            </div>
          </div>
        )}

        {/* ── Hero ──────────────────────────────────────────── */}
        <div style={{ display: 'flex', gap: 40, alignItems: 'flex-start', marginBottom: 32, paddingBottom: 32, borderBottom: '1px solid var(--border)' }}>
          {/* Risk verdict — the money shot */}
          <div style={{ flexShrink: 0, textAlign: 'center' }}>
            <div style={{ fontSize: 11, fontWeight: 600, letterSpacing: '0.1em', textTransform: 'uppercase', color: 'var(--tx-3)', marginBottom: 8 }}>
              Risk level
            </div>
            <div style={{
              fontSize: 72, fontWeight: 800, lineHeight: 1, color: riskColor,
              letterSpacing: '-0.03em', fontVariantNumeric: 'tabular-nums',
            }}>
              {report.riskLevel}
            </div>
            <div style={{ marginTop: 12, fontSize: 13, color: 'var(--tx-3)', fontFamily: 'monospace' }}>
              score: <span style={{ color: riskColor, fontWeight: 700 }}>{report.score}</span> / 100
            </div>
          </div>

          {/* Subject meta + score gauge */}
          <div style={{ flex: 1, paddingTop: 4 }}>
            <h1 style={{ fontSize: 26, fontWeight: 700, color: 'var(--tx)', letterSpacing: '-0.02em', marginBottom: 16 }}>
              {report.subject?.fullName}
            </h1>

            {/* Two clearly separated groups: subject attributes vs check metadata */}
            <div style={{ display: 'flex', gap: 0, marginBottom: 20, flexWrap: 'wrap' }}>

              {/* Subject attributes */}
              <div style={{ display: 'flex', gap: 20, paddingRight: 20, marginRight: 20, borderRight: '1px solid var(--border)', flexWrap: 'wrap' }}>
                {report.subject?.dateOfBirth && (
                  <MetaField label="Date of birth" value={formatDateAU(report.subject.dateOfBirth)} />
                )}
                {report.subject?.nationality && (
                  <MetaField label="Nationality" value={`${NATIONALITY_LABELS[report.subject.nationality] || report.subject.nationality} (${report.subject.nationality})`} />
                )}
                {report.subject?.walletAddress && (
                  <MetaField label="Wallet" value={`${report.subject.walletAddress.slice(0, 12)}...`} mono />
                )}
              </div>

              {/* Check metadata */}
              <div style={{ display: 'flex', gap: 20, flexWrap: 'wrap' }}>
                <MetaField label="Searched" value={new Date(report.createdAt).toLocaleDateString('en-AU', { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' })} />
                <MetaField label="Completed in" value={`${(report.durationMs / 1000).toFixed(1)}s`} mono />
              </div>
            </div>

            <ScoreGauge score={report.score} riskLevel={report.riskLevel} />

          </div>
        </div>

        {/* ── AI Summary ───────────────────────────────────── */}
        {report.explanation && (
          <div style={{ marginBottom: 28, padding: '16px 20px', background: 'var(--surface)', border: '1px solid var(--border)', borderLeft: '3px solid var(--accent)', borderRadius: 8 }}>
            <div style={{ fontSize: 10, fontWeight: 600, color: 'var(--accent)', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 10 }}>
              Analysis summary
            </div>
            <p style={{ fontSize: 13, color: 'var(--tx-2)', lineHeight: 1.75, margin: 0 }}>
              {report.explanation}
            </p>
          </div>
        )}

        {/* ── Recommendations ──────────────────────────────── */}
        {report.recommendations?.length > 0 && (
          <div style={{ marginBottom: 28 }}>
            <h2 style={S.sectionHead}>Recommendations</h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              {report.recommendations.map((r, i) => (
                <div key={i} style={{ display: 'flex', gap: 12, padding: '10px 14px', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 6 }}>
                  <span style={{ fontSize: 11, fontWeight: 700, color: 'var(--tx-3)', minWidth: 18, paddingTop: 1, fontFamily: 'monospace' }}>{String(i + 1).padStart(2, '0')}</span>
                  <span style={{ fontSize: 13, color: 'var(--tx-2)', lineHeight: 1.5 }}>{r}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ── Layer results ─────────────────────────────────── */}
        <div style={{ marginBottom: 28 }}>
          <h2 style={S.sectionHead}>Layer results</h2>
          <div style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 8, overflow: 'hidden' }}>
            {/* Header row */}
            <div style={{ display: 'grid', gridTemplateColumns: COLS, padding: '8px 16px', borderBottom: '1px solid var(--border)', fontSize: 10, fontWeight: 600, color: 'var(--tx-3)', letterSpacing: '0.08em', textTransform: 'uppercase' }}>
              <span>Layer</span><span>Result</span><span>Score</span><span>Time</span><span />
            </div>
            {layers.map(([key, layer], idx) => {
              const hasIssue = layer.hardStop || layer.pepConfirmed || layer.findingsCount > 0 || layer.disqualifiedDirector || layer.status === 'error'
              const dotColor = layer.status === 'error' ? 'var(--red)' : hasIssue ? 'var(--amber)' : 'var(--green)'
              const isOpen = open[key]

              // Inline flags that must be visible without expanding
              const countryMismatches = key === 'pep'
                ? [...(layer.strongMatches || []), ...(layer.possibleMatches || [])].filter(m => m._countryMismatch)
                : []
              const hasMismatchFlag = countryMismatches.length > 0

              return (
                <div key={key} style={{ borderBottom: idx < layers.length - 1 ? '1px solid var(--border)' : 'none' }}>
                  <div
                    onClick={() => toggle(key)}
                    style={{ display: 'grid', gridTemplateColumns: COLS, padding: '11px 16px', cursor: 'pointer', alignItems: 'center', transition: 'background 0.08s' }}
                    onMouseEnter={e => e.currentTarget.style.background = 'var(--raised)'}
                    onMouseLeave={e => e.currentTarget.style.background = 'transparent'}
                  >
                    <span style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 13, fontWeight: 500, color: 'var(--tx)' }}>
                      <span style={{ color: dotColor, fontSize: 8 }}>●</span>
                      {LAYER_NAME[key] || key}
                    </span>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                      <span style={{ fontSize: 12, color: 'var(--tx-3)' }}>{layer.summary}</span>
                      {hasMismatchFlag && (
                        <span style={{
                          display: 'inline-flex', alignItems: 'center', gap: 4,
                          fontSize: 10, fontWeight: 600, color: 'var(--amber)',
                          background: 'rgba(255,170,0,0.14)',
                          borderRadius: 3, padding: '2px 7px',
                          alignSelf: 'flex-start', whiteSpace: 'nowrap',
                        }}>
                          <AlertTriangle size={9} strokeWidth={2.5} />
                          Country mismatch - verify manually
                        </span>
                      )}
                    </div>
                    <span style={{ fontSize: 12, fontFamily: 'monospace', fontWeight: 700, color: layer.scoreContribution > 0 ? 'var(--amber)' : 'var(--tx-3)' }}>
                      {layer.scoreContribution > 0 ? `+${layer.scoreContribution}` : '-'}
                    </span>
                    <span style={{ fontSize: 11, color: 'var(--tx-3)', fontFamily: 'monospace' }}>{layer.durationMs}ms</span>
                    <span style={{ color: 'var(--tx-3)', display: 'flex', justifyContent: 'flex-end' }}>
                      {isOpen ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
                    </span>
                  </div>
                  {isOpen && (
                    <div style={{ background: 'var(--bg)', borderTop: '1px solid var(--border)', padding: '16px 20px' }}>
                      <LayerDetail layerKey={key} layer={layer} subject={report.subject} />
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        </div>

        {/* Sources + disclaimer */}
        <div style={{ padding: '14px 16px', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 8, marginBottom: 16 }}>
          <div style={{ fontSize: 10, fontWeight: 600, color: 'var(--tx-3)', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 8 }}>Sources queried</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
            {(report.meta?.sourcesQueried || []).map(s => (
              <span key={s} style={{ fontSize: 11, color: 'var(--tx-3)', background: 'var(--raised)', border: '1px solid var(--border)', borderRadius: 4, padding: '2px 8px' }}>{s}</span>
            ))}
          </div>
        </div>

        <p style={{ fontSize: 11, color: 'var(--tx-3)', lineHeight: 1.7, opacity: 0.6 }}>
          {report.meta?.disclaimer}
        </p>
      </div>
    </div>
  )
}

const COLS = '200px 1fr 70px 80px 32px'
const S = {
  sectionHead: { fontSize: 12, fontWeight: 600, color: 'var(--tx-3)', letterSpacing: '0.07em', textTransform: 'uppercase', marginBottom: 12 },
  dropItem: { display: 'flex', alignItems: 'flex-start', gap: 10, width: '100%', padding: '11px 14px', background: 'none', border: 'none', color: 'var(--tx-2)', cursor: 'pointer', fontSize: 12, textAlign: 'left', transition: 'background 0.1s' },
}

function MetaField({ label, value, mono }) {
  if (!value) return null
  return (
    <div>
      <div style={{ fontSize: 10, fontWeight: 600, color: 'var(--tx-3)', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 3 }}>{label}</div>
      <div style={{ fontSize: 13, color: 'var(--tx-2)', fontFamily: mono ? 'monospace' : 'inherit' }}>{value}</div>
    </div>
  )
}

const NATIONALITY_LABELS = {
  AU:'Australia', GB:'United Kingdom', US:'United States', NZ:'New Zealand',
  CA:'Canada', IE:'Ireland', DE:'Germany', FR:'France', IT:'Italy', ES:'Spain',
  NL:'Netherlands', BE:'Belgium', CH:'Switzerland', AT:'Austria', SE:'Sweden',
  NO:'Norway', DK:'Denmark', FI:'Finland', JP:'Japan', CN:'China', IN:'India',
  SG:'Singapore', HK:'Hong Kong', ZA:'South Africa', BR:'Brazil', MX:'Mexico',
  RU:'Russia', AE:'United Arab Emirates', SA:'Saudi Arabia',
}

function SevBadge({ sev }) {
  const c = sev === 'CRITICAL' ? '#ff4d4d' : sev === 'SIGNIFICANT' ? '#ffaa00' : '#8b949e'
  return (
    <span style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.06em', color: c, background: `${c}18`, border: `1px solid ${c}40`, borderRadius: 4, padding: '2px 7px' }}>
      {sev}
    </span>
  )
}

function MatchBadge({ verdict }) {
  const confirmed = verdict === 'STRONG_MATCH'
  return (
    <span style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.06em', color: confirmed ? 'var(--amber)' : 'var(--tx-3)', background: confirmed ? 'rgba(255,170,0,0.1)' : 'var(--raised)', border: `1px solid ${confirmed ? 'rgba(255,170,0,0.3)' : 'var(--border)'}`, borderRadius: 4, padding: '2px 7px' }}>
      {confirmed ? 'CONFIRMED MATCH' : 'POSSIBLE MATCH'}
    </span>
  )
}

function Row({ label, value, mono }) {
  if (!value) return null
  return (
    <div style={{ display: 'flex', gap: 12, marginBottom: 5 }}>
      <span style={{ fontSize: 11, color: 'var(--tx-3)', minWidth: 120, flexShrink: 0 }}>{label}</span>
      <span style={{ fontSize: 12, color: 'var(--tx-2)', fontFamily: mono ? 'monospace' : 'inherit', wordBreak: 'break-all' }}>{value}</span>
    </div>
  )
}

function Divider() {
  return <div style={{ height: 1, background: 'var(--border)', margin: '14px 0' }} />
}

function NoResults({ text }) {
  return <p style={{ fontSize: 12, color: 'var(--tx-3)', margin: 0 }}>{text}</p>
}

function LayerDetail({ layerKey, layer, subject }) {
  if (layerKey === 'pep') return <PepDetail layer={layer} subject={subject} />
  if (layerKey === 'adverseMedia') return <MediaDetail layer={layer} />
  if (layerKey === 'sanctions') return <SanctionsDetail layer={layer} />
  if (layerKey === 'corporate') return <CorporateDetail layer={layer} />
  if (layerKey === 'crypto') return <CryptoDetail layer={layer} />
  return <NoResults text="No detail available." />
}

function PepDetail({ layer, subject }) {
  const all = [...(layer.strongMatches || []), ...(layer.possibleMatches || [])]
  if (!all.length) return (
    <NoResults text={`No PEP indicators found. Sources queried: ${(layer.sourcesQueried || []).join(', ')}.`} />
  )
  return (
    <div>
      {all.map((m, i) => (
        <div key={i}>
          {i > 0 && <Divider />}
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
            <MatchBadge verdict={m.verdict} />
            <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--tx)' }}>{m.matchedName}</span>
          </div>

          {/* Country mismatch warning — must be prominent */}
          {m._countryMismatch && subject?.nationality && (
            <div style={{ display: 'flex', gap: 10, padding: '10px 14px', background: 'rgba(255,170,0,0.06)', border: '1px solid rgba(255,170,0,0.3)', borderRadius: 6, marginBottom: 12 }}>
              <AlertTriangle size={14} color="var(--amber)" style={{ flexShrink: 0, marginTop: 1 }} />
              <div style={{ fontSize: 12, color: 'var(--amber)', lineHeight: 1.6 }}>
                <strong>Country mismatch detected.</strong> The subject's declared nationality is{' '}
                <strong>{NATIONALITY_LABELS[subject.nationality] || subject.nationality} ({subject.nationality})</strong>, but this
                Wikidata entity is associated with <strong>{m.country}</strong>. This is likely a different person
                sharing the same name. The result has been flagged as a possible match - not confirmed - and
                requires manual verification before any action is taken.
              </div>
            </div>
          )}

          <Row label="Source" value={m.sourceName || m.source} />
          <Row label="Classification" value={m.pepClassification?.label} />
          <Row label="Match confidence" value={m.score ? `${(m.score * 100).toFixed(0)}%` : null} />
          {m.positions?.length > 0 && (
            <div style={{ display: 'flex', gap: 12, marginBottom: 5 }}>
              <span style={{ fontSize: 11, color: 'var(--tx-3)', minWidth: 120, flexShrink: 0 }}>Positions held</span>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
                {m.positions.filter(p => p !== 'politician').map((p, j) => (
                  <span key={j} style={{ fontSize: 12, color: 'var(--tx-2)' }}>• {p}</span>
                ))}
              </div>
            </div>
          )}
          <Row label="Country" value={m.country} />
          <Row label="Date of birth" value={m.birthDate} mono />
          {m.url && (
            <div style={{ display: 'flex', gap: 12, marginTop: 8 }}>
              <span style={{ fontSize: 11, color: 'var(--tx-3)', minWidth: 120, flexShrink: 0 }}>Source record</span>
              <a href={m.url} target="_blank" rel="noopener noreferrer" style={{ fontSize: 12, color: 'var(--accent)', wordBreak: 'break-all' }}>{m.url}</a>
            </div>
          )}
        </div>
      ))}
      {layer.note && (
        <>
          <Divider />
          <p style={{ fontSize: 11, color: 'var(--tx-3)', lineHeight: 1.7, margin: 0, fontStyle: 'italic' }}>{layer.note}</p>
        </>
      )}
    </div>
  )
}

function MediaDetail({ layer }) {
  if (!layer.findings?.length) return (
    <NoResults text={`No adverse media findings. Sources queried: ${(layer.sourcesQueried || []).join(', ')}.`} />
  )
  return (
    <div>
      {layer.findings.map((f, i) => (
        <div key={i}>
          {i > 0 && <Divider />}
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
            <SevBadge sev={f.severity} />
            <span style={{ fontSize: 12, color: 'var(--tx-3)' }}>{f.sourceName || f.source}</span>
            {f.publishedAt && <span style={{ fontSize: 11, color: 'var(--tx-3)', marginLeft: 'auto' }}>{f.publishedAt.slice(0, 10)}</span>}
          </div>
          {f.title && <p style={{ fontSize: 13, fontWeight: 500, color: 'var(--tx)', marginBottom: 8, lineHeight: 1.5 }}>{f.title}</p>}
          {f.summary && <p style={{ fontSize: 12, color: 'var(--tx-3)', marginBottom: 8, lineHeight: 1.6 }}>{f.summary}</p>}
          {f.keywords?.length > 0 && (
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 5, marginBottom: 8 }}>
              {f.keywords.map(k => (
                <span key={k} style={{ fontSize: 11, color: 'var(--red)', background: 'rgba(255,77,77,0.08)', border: '1px solid rgba(255,77,77,0.2)', borderRadius: 4, padding: '2px 7px' }}>{k}</span>
              ))}
            </div>
          )}
          {f.url && <a href={f.url} target="_blank" rel="noopener noreferrer" style={{ fontSize: 11, color: 'var(--accent)', wordBreak: 'break-all' }}>{f.url}</a>}
        </div>
      ))}
    </div>
  )
}

function SanctionsDetail({ layer }) {
  const hits = layer.hits || []
  if (!hits.length) return (
    <NoResults text={`No sanctions matches found. Sources queried: ${(layer.sourcesQueried || []).join(', ')}.`} />
  )
  return (
    <div>
      {hits.map((h, i) => (
        <div key={i}>
          {i > 0 && <Divider />}
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
            <span style={{ fontSize: 10, fontWeight: 700, color: 'var(--red)', background: 'rgba(255,77,77,0.1)', border: '1px solid rgba(255,77,77,0.3)', borderRadius: 4, padding: '2px 7px' }}>SANCTIONS HIT</span>
            <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--tx)' }}>{h.matchedName || h.caption}</span>
          </div>
          <Row label="Source" value={h.sourceName || h.source} />
          <Row label="Match score" value={h.score ? `${(h.score * 100).toFixed(0)}%` : null} />
          <Row label="Datasets" value={h.datasets?.join(', ')} />
          {h.url && (
            <div style={{ display: 'flex', gap: 12, marginTop: 8 }}>
              <span style={{ fontSize: 11, color: 'var(--tx-3)', minWidth: 120 }}>Source record</span>
              <a href={h.url} target="_blank" rel="noopener noreferrer" style={{ fontSize: 12, color: 'var(--accent)' }}>{h.url}</a>
            </div>
          )}
        </div>
      ))}
    </div>
  )
}

function CorporateDetail({ layer }) {
  const companies = layer.companies || []
  if (!companies.length && !layer.flags?.length) return (
    <NoResults text={`No corporate matches or flags found. Sources queried: ${(layer.sourcesQueried || []).join(', ')}.`} />
  )
  return (
    <div>
      {layer.flags?.map((flag, i) => (
        <div key={i} style={{ padding: '8px 12px', background: 'rgba(255,170,0,0.06)', border: '1px solid rgba(255,170,0,0.25)', borderRadius: 6, marginBottom: 10, fontSize: 12, color: 'var(--amber)' }}>
          ⚑ {flag.replace(/_/g, ' ')}
        </div>
      ))}
      {companies.map((c, i) => (
        <div key={i}>
          {i > 0 && <Divider />}
          <p style={{ fontSize: 13, fontWeight: 600, color: 'var(--tx)', marginBottom: 8 }}>{c.name}</p>
          <Row label="Company number" value={c.companyNumber} mono />
          <Row label="Jurisdiction" value={c.jurisdiction} />
          <Row label="Status" value={c.status} />
          <Row label="Incorporated" value={c.incorporationDate} mono />
          <Row label="Source" value={c.source} />
        </div>
      ))}
    </div>
  )
}

function CryptoDetail({ layer }) {
  const flags = layer.flags || []
  if (!flags.length && !layer.criticalFlagCount && !layer.highFlagCount) return (
    <NoResults text={`No on-chain risk flags detected for the provided wallet address.`} />
  )
  return (
    <div>
      <Row label="Wallet address" value={layer.walletAddress} mono />
      <Row label="Chain" value={layer.chain} />
      {flags.map((f, i) => (
        <div key={i}>
          {i > 0 && <Divider />}
          <SevBadge sev={f.severity} />
          <p style={{ fontSize: 13, fontWeight: 500, color: 'var(--tx)', margin: '8px 0 4px' }}>{f.description || f.type}</p>
          <Row label="Source" value={f.source} />
        </div>
      ))}
    </div>
  )
}
